FROM python:latest
WORKDIR /tmp
ADD requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY jga_bibliography.py jga_bibliography.py
COPY . /tmp/
CMD ["./wait-for-it.sh", "db:5432", "--","python", "-u", "jga_bibliography.py"]
